server.port=8081
spring.application.name=auth-service

# Pointing ONLY to the auth_db we created in Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

security.jwt.secret=AnkapMarketplaceSuperSecretKey32
security.jwt.issuer=ankap-marketplace
security.jwt.access-token-minutes=15