
spring.application.name=ankap-marketplace-service

# =======================
# DB (PostgreSQL)
# =======================
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=marketplace
spring.datasource.password=marketplace
spring.datasource.driver-class-name=org.postgresql.Driver

# =======================
# JPA / Hibernate
# =======================
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.flywaydb=DEBUG
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true

# Optional for debugging SQL (can be noisy)
# spring.jpa.show-sql=true
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

# =======================
# Flyway
# =======================
spring.flyway.enabled=true

# =======================
# Server
# =======================
server.port=8080