server.port=8082
spring.application.name=product-service

# Pointing ONLY to the product_db
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Let Hibernate create tables for us just for this rapid prototyping phase
spring.jpa.hibernate.ddl-auto=update

# MUST match the secret from Auth Service!
security.jwt.secret=AnkapMarketplaceSuperSecretKey32