package com.ankap.platform.orderservice.application.service;

import com.ankap.platform.orderservice.application.port.in.PlaceOrderCommand;
import com.ankap.platform.orderservice.application.port.in.PlaceOrderUseCase;
import com.ankap.platform.orderservice.application.port.out.OrderEventPublisherPort;
import com.ankap.platform.orderservice.application.port.out.OrderRepositoryPort;
import com.ankap.platform.orderservice.application.port.out.ProductCheckPort;
import com.ankap.platform.orderservice.domain.Order;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

public class PlaceOrderService implements PlaceOrderUseCase {

    private final OrderRepositoryPort repositoryPort;
    private final ProductCheckPort productCheckPort;
    private final OrderEventPublisherPort eventPublisherPort;

    public PlaceOrderService(OrderRepositoryPort repositoryPort, ProductCheckPort productCheckPort, OrderEventPublisherPort eventPublisherPort) {
        this.repositoryPort = repositoryPort;
        this.productCheckPort = productCheckPort;
        this.eventPublisherPort = eventPublisherPort;
    }

    @Override
    public Order placeOrder(PlaceOrderCommand command) {
        if (!productCheckPort.hasEnoughInventory(command.productId(), command.quantity())) {
            throw new IllegalArgumentException("Insufficient stock for product: " + command.productId());
        }

        BigDecimal price = productCheckPort.getProductPrice(command.productId());
        BigDecimal totalPrice = price.multiply(BigDecimal.valueOf(command.quantity()));

        Order order = new Order(
                null, // Generated by DB
                command.productId(),
                command.buyerEmail(),
                command.quantity(),
                totalPrice,
                "PENDING",
                Instant.now()
        );

        Order savedOrder = repositoryPort.save(order);
        eventPublisherPort.publishOrderPlacedEvent(savedOrder);

        return savedOrder;
    }
}